# AUTO-GENERATED by the Config Generation GUI page — do not edit by hand.
# Reflects every config in code/pipeline/configs/ as of the last Generate run.

declare -A SUBJECT_CONFIGS
declare -A SUBJECT_TIMELIMITS

SUBJECT_CONFIGS["41Y01"]="${BASE_CONFIG_DIR}/sub-41Y01_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y01"]="02:00:00"

SUBJECT_CONFIGS["41Y03"]="${BASE_CONFIG_DIR}/sub-41Y03_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y03"]="02:00:00"

SUBJECT_CONFIGS["41Y04"]="${BASE_CONFIG_DIR}/sub-41Y04_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y04"]="02:00:00"

SUBJECT_CONFIGS["41Y05"]="${BASE_CONFIG_DIR}/sub-41Y05_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y05"]="02:00:00"

SUBJECT_CONFIGS["41Y06"]="${BASE_CONFIG_DIR}/sub-41Y06_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y06"]="02:00:00"

SUBJECT_CONFIGS["41Y07"]="${BASE_CONFIG_DIR}/sub-41Y07_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y07"]="02:00:00"

SUBJECT_CONFIGS["41Y08"]="${BASE_CONFIG_DIR}/sub-41Y08_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y08"]="02:00:00"

SUBJECT_CONFIGS["41Y09"]="${BASE_CONFIG_DIR}/sub-41Y09_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y09"]="02:00:00"

SUBJECT_CONFIGS["41Y10"]="${BASE_CONFIG_DIR}/sub-41Y10_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y10"]="02:00:00"

SUBJECT_CONFIGS["41Y11"]="${BASE_CONFIG_DIR}/sub-41Y11_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y11"]="02:00:00"

SUBJECT_CONFIGS["41Y12"]="${BASE_CONFIG_DIR}/sub-41Y12_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y12"]="02:00:00"

SUBJECT_CONFIGS["41Y14"]="${BASE_CONFIG_DIR}/sub-41Y14_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y14"]="02:00:00"

SUBJECT_CONFIGS["41Y15"]="${BASE_CONFIG_DIR}/sub-41Y15_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y15"]="02:00:00"

SUBJECT_CONFIGS["41Y16"]="${BASE_CONFIG_DIR}/sub-41Y16_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y16"]="02:00:00"

SUBJECT_CONFIGS["41Y17"]="${BASE_CONFIG_DIR}/sub-41Y17_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y17"]="02:00:00"

SUBJECT_CONFIGS["41Y18"]="${BASE_CONFIG_DIR}/sub-41Y18_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y18"]="02:00:00"

SUBJECT_CONFIGS["41Y19"]="${BASE_CONFIG_DIR}/sub-41Y19_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y19"]="02:00:00"

SUBJECT_CONFIGS["41Y20"]="${BASE_CONFIG_DIR}/sub-41Y20_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y20"]="02:00:00"

SUBJECT_CONFIGS["41Y21"]="${BASE_CONFIG_DIR}/sub-41Y21_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y21"]="02:00:00"

SUBJECT_CONFIGS["41Y22"]="${BASE_CONFIG_DIR}/sub-41Y22_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y22"]="02:00:00"

SUBJECT_CONFIGS["41Y23"]="${BASE_CONFIG_DIR}/sub-41Y23_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y23"]="02:00:00"

SUBJECT_CONFIGS["41Y24"]="${BASE_CONFIG_DIR}/sub-41Y24_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y24"]="02:00:00"

SUBJECT_CONFIGS["41Y25"]="${BASE_CONFIG_DIR}/sub-41Y25_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y25"]="02:00:00"

SUBJECT_CONFIGS["41Y27"]="${BASE_CONFIG_DIR}/sub-41Y27_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y27"]="02:00:00"

SUBJECT_CONFIGS["41Y28"]="${BASE_CONFIG_DIR}/sub-41Y28_roi-striatum_ROI_ex_focality.json"
SUBJECT_TIMELIMITS["41Y28"]="02:00:00"

SUBJECT_CONFIGS["52Y02"]="${BASE_CONFIG_DIR}/sub-52Y02_roi-STN_L_roi_Allen_ex_focality.json"
SUBJECT_TIMELIMITS["52Y02"]="02:00:00"

SUBJECT_CONFIGS["52Y03"]="${BASE_CONFIG_DIR}/sub-52Y03_roi-STN_L_roi_Allen_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-52Y03_roi-STN_L_roi_Allen_ex_mean.json"
SUBJECT_TIMELIMITS["52Y03"]="02:00:00"

SUBJECT_CONFIGS["52Y04"]="${BASE_CONFIG_DIR}/sub-52Y04_roi-STN_L_roi_Allen_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-52Y04_roi-STN_L_roi_Allen_ex_mean.json"
SUBJECT_TIMELIMITS["52Y04"]="02:00:00"

SUBJECT_CONFIGS["52Y05"]="${BASE_CONFIG_DIR}/sub-52Y05_roi-STN_L_roi_Allen_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-52Y05_roi-STN_L_roi_Allen_ex_mean.json"
SUBJECT_TIMELIMITS["52Y05"]="02:00:00"

SUBJECT_CONFIGS["52Y07"]="${BASE_CONFIG_DIR}/sub-52Y07_roi-STN_L_roi_Allen_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-52Y07_roi-STN_L_roi_Allen_ex_mean.json"
SUBJECT_TIMELIMITS["52Y07"]="02:00:00"

SUBJECT_CONFIGS["52Y08"]="${BASE_CONFIG_DIR}/sub-52Y08_roi-STN_L_roi_Allen_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-52Y08_roi-STN_L_roi_Allen_ex_mean.json"
SUBJECT_TIMELIMITS["52Y08"]="02:00:00"

SUBJECT_CONFIGS["52Y09"]="${BASE_CONFIG_DIR}/sub-52Y09_roi-STN_L_roi_Allen_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-52Y09_roi-STN_L_roi_Allen_ex_mean.json"
SUBJECT_TIMELIMITS["52Y09"]="02:00:00"

SUBJECT_CONFIGS["52Y10"]="${BASE_CONFIG_DIR}/sub-52Y10_roi-STN_L_roi_Allen_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-52Y10_roi-STN_L_roi_Allen_ex_mean.json"
SUBJECT_TIMELIMITS["52Y10"]="02:00:00"

SUBJECT_CONFIGS["52Y13"]="${BASE_CONFIG_DIR}/sub-52Y13_roi-STN_L_roi_Allen_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-52Y13_roi-STN_L_roi_Allen_ex_mean.json"
SUBJECT_TIMELIMITS["52Y13"]="02:00:00"

SUBJECT_CONFIGS["73A01"]="${BASE_CONFIG_DIR}/sub-73A01_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73A01"]="02:00:00"

SUBJECT_CONFIGS["73A02"]="${BASE_CONFIG_DIR}/sub-73A02_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73A02"]="02:00:00"

SUBJECT_CONFIGS["73A03"]="${BASE_CONFIG_DIR}/sub-73A03_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73A03"]="02:00:00"

SUBJECT_CONFIGS["73A04"]="${BASE_CONFIG_DIR}/sub-73A04_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73A04"]="02:00:00"

SUBJECT_CONFIGS["73A05"]="${BASE_CONFIG_DIR}/sub-73A05_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73A05"]="02:00:00"

SUBJECT_CONFIGS["73A06"]="${BASE_CONFIG_DIR}/sub-73A06_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73A06"]="02:00:00"

SUBJECT_CONFIGS["73A07"]="${BASE_CONFIG_DIR}/sub-73A07_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73A07"]="02:00:00"

SUBJECT_CONFIGS["73A08"]="${BASE_CONFIG_DIR}/sub-73A08_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73A08"]="02:00:00"

SUBJECT_CONFIGS["73T01"]="${BASE_CONFIG_DIR}/sub-73T01_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T01_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T01_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T01"]="02:00:00"

SUBJECT_CONFIGS["73T02"]="${BASE_CONFIG_DIR}/sub-73T02_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T02_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T02_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T02"]="02:00:00"

SUBJECT_CONFIGS["73T03"]="${BASE_CONFIG_DIR}/sub-73T03_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T03_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T03_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T03"]="02:00:00"

SUBJECT_CONFIGS["73T04"]="${BASE_CONFIG_DIR}/sub-73T04_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T04_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T04_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T04"]="02:00:00"

SUBJECT_CONFIGS["73T05"]="${BASE_CONFIG_DIR}/sub-73T05_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T05_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T05_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T05"]="02:00:00"

SUBJECT_CONFIGS["73T06"]="${BASE_CONFIG_DIR}/sub-73T06_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T06_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T06_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T06"]="02:00:00"

SUBJECT_CONFIGS["73T07"]="${BASE_CONFIG_DIR}/sub-73T07_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T07_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T07_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T07"]="02:00:00"

SUBJECT_CONFIGS["73T09"]="${BASE_CONFIG_DIR}/sub-73T09_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T09_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T09_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T09"]="02:00:00"

SUBJECT_CONFIGS["73T10"]="${BASE_CONFIG_DIR}/sub-73T10_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T10_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T10_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T10"]="02:00:00"

SUBJECT_CONFIGS["73T11"]="${BASE_CONFIG_DIR}/sub-73T11_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T11_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T11_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T11"]="02:00:00"

SUBJECT_CONFIGS["73T12"]="${BASE_CONFIG_DIR}/sub-73T12_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T12_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T12_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T12"]="02:00:00"

SUBJECT_CONFIGS["73T14"]="${BASE_CONFIG_DIR}/sub-73T14_roi-hippo_r_phg_ex_focality.json \
  ${BASE_CONFIG_DIR}/sub-73T14_roi-hippo_r_phg_ex_mean.json \
  ${BASE_CONFIG_DIR}/sub-73T14_roi-right_hc_phg_hierarchical_BNA_ex_focality.json"
SUBJECT_TIMELIMITS["73T14"]="02:00:00"
