#!/bin/bash
# ==============================================================================
# Multi-ROI batch submitter — SCITAS JED (Apptainer / SLURM)
# ==============================================================================
#
# Submits ONE job per subject.  All ROI/goal configs for that subject are
# passed together to a single run_pipeline.py call, which processes them
# sequentially.  The TDCS leadfield (the expensive part, ~30 min) is computed
# once on the first config and then reused for every subsequent one — no
# race conditions when the leadfield does not yet exist.
#
# PREREQUISITES
# -------------
# 1. BIDS folder on scratch: /scratch/$USER/BIDS_TI_Toolbox/
# 2. charm must have been run (produces m2m_<subj>/ with aseg.auto.mgz)
# 3. The Apptainer image must exist:
#       /work/uphummel/shared/software/containers/simnibs/simnibs_v2.3.0.sif
#
# USAGE (from SCITAS login node)
# -----
#   cd /scratch/$USER/BIDS_TI_Toolbox/code/pipeline
#   bash submit_multiroi_scitas.sh                        # all subjects, all goals
#   bash submit_multiroi_scitas.sh --goal mean            # mean only (phase 1 — builds leadfield)
#   bash submit_multiroi_scitas.sh --goal mean 002 035    # mean only, specific subjects
#
# Each job logs to:
#   /scratch/$USER/logs/simnibs/simnibs_<subj>_allrois_<jobid>.out/.err
#
# ADDING NEW SUBJECTS / ROIs
#   Edit generate_configs.py (SUBJECTS / ROIS lists), then run:
#     python generate_configs.py
#   That regenerates all JSON configs AND subject_configs.sh automatically.
#   No manual edits to this script are needed.
#
# TIME BUDGET (per subject — estimated by generate_configs.py)
#   Leadfield computation : ~30 min  (computed once, reused for all ROIs)
#   Exhaustive search     : ~5 min   per ROI/goal combo
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SBATCH_SCRIPT="${SCRIPT_DIR}/simnibs_ti_pipeline.sbatch"
BASE_CONFIG_DIR="/mnt/BIDS_TI_Toolbox/code/pipeline/configs"
LOG_DIR="/scratch/${USER}/logs/simnibs"

mkdir -p "$LOG_DIR"

# ==============================================================================
# Load per-subject config lists (auto-generated by generate_configs.py)
# ==============================================================================

ENV_FILE="${SCRIPT_DIR}/subject_configs.sh"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: ${ENV_FILE} not found."
  echo "       Run: python generate_configs.py"
  exit 1
fi
# shellcheck source=subject_configs.sh
source "$ENV_FILE"

# Parse arguments: optional --goal filter, then optional subject IDs.
GOAL_FILTER=""
TIME_OVERRIDE=""
REQUESTED_SUBJECTS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --goal) GOAL_FILTER="$2"; shift 2 ;;
    --time) TIME_OVERRIDE="$2"; shift 2 ;;
    *) REQUESTED_SUBJECTS+=("$1"); shift ;;
  esac
done

if [[ ${#REQUESTED_SUBJECTS[@]} -gt 0 ]]; then
  RUN_SUBJECTS=("${REQUESTED_SUBJECTS[@]}")
else
  RUN_SUBJECTS=("${!SUBJECT_CONFIGS[@]}")
fi

# ==============================================================================
# Submission loop — one job per subject
# ==============================================================================

echo "============================================================"
echo " Submitting multi-ROI TI batch — $(date)"
echo " Subjects : ${RUN_SUBJECTS[*]}"
echo " Goal     : ${GOAL_FILTER:-all}"
echo " Account  : uphummel"
echo " CPUs     : 8 per job  |  Mem: 32G per job"
echo " Mode     : one job per subject (leadfield shared across ROIs)"
echo "============================================================"

for subj in "${RUN_SUBJECTS[@]}"; do
  if [[ -z "${SUBJECT_CONFIGS[$subj]+x}" ]]; then
    echo "  [warn] sub-${subj} not found in subject_configs.sh — skipping"
    continue
  fi
  cfgs="${SUBJECT_CONFIGS[$subj]}"
  # Filter by goal if requested (e.g. --goal mean keeps only *_ex_mean*.json)
  if [[ -n "$GOAL_FILTER" ]]; then
    cfgs=$(echo "$cfgs" | tr ' ' '\n' | grep "_ex_${GOAL_FILTER}" | tr '\n' ' ')
  fi
  [[ -z "${cfgs// /}" ]] && { echo "  [skip] sub-${subj} — no configs match goal '${GOAL_FILTER}'"; continue; }
  tlimit="${TIME_OVERRIDE:-${SUBJECT_TIMELIMITS[$subj]}}"
  n_cfgs=$(echo "$cfgs" | wc -w)

  job_id=$(sbatch \
    --job-name="ti_${subj}_allrois" \
    --time="${tlimit}" \
    --output="${LOG_DIR}/simnibs_${subj}_allrois_%j.out" \
    --error="${LOG_DIR}/simnibs_${subj}_allrois_%j.err" \
    --export=ALL,PIPELINE_CONFIGS="${cfgs}",PIPELINE_EXTRA_ARGS="--force optimization" \
    "$SBATCH_SCRIPT" \
    | awk '{print $NF}')

  echo ""
  echo "  Submitted sub-${subj}: job ${job_id}  (time=${tlimit}, ${n_cfgs} configs)"
  echo "    log : ${LOG_DIR}/simnibs_${subj}_allrois_${job_id}.out"
done

echo ""
echo "============================================================"
echo " All jobs submitted. Monitor with:"
echo "   squeue -u \$USER"
echo "   tail -f ${LOG_DIR}/simnibs_<subj>_allrois_<jobid>.out"
echo "============================================================"
